language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
install:
  - npm install
script:
  - npm test
after_success:
  - pip install --user codecov
  - nyc report --reporter=text-lcov > coverage/lcov.info
  - codecov --file coverage/lcov.info
